/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Reportes;

import java.awt.Color;
import java.net.URL;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import modelo.Conexion;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author darwi
 */
public class Reporte extends javax.swing.JDialog {
Date fecha,fecha2;
String sentenciaSQL;
Connection con= null;
Conexion conecta;
    /**
     * Creates new form Reporte
     */
    public Reporte(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
      
    }
public void conectarBD() {
        conecta = new Conexion();
        con = conecta.getConexion();
    }

public void llamarReportes(String nombre)
     {
        try {
            conectarBD();
            //RUTA DEL ARCHIVO
            URL urlMaestro=getClass().getResource(nombre);
            //LLAMADO DEL ARCHIVO
            JasperReport reporte =(JasperReport) JRLoader.loadObject(urlMaestro);
            //LLENAMOS EL REPORTE
            JasperPrint jprint=JasperFillManager.fillReport(reporte, null,con);
            //VISTA DEL REPORTE
            JasperViewer view= new JasperViewer(jprint,false);
            //TITULO OPCIONAL
            view.setTitle("ABARROTERIA RIOS");
            //CIERRE DEL REPORTE
            view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            view.setVisible(true);
            con.close();
        } catch (JRException ex) {
            System.out.print(ex.getMessage());
        } catch (SQLException ex) {
           System.out.print(ex.getMessage());
        }
     }
     
     public void llamarReportePorfecha()
     {
       String f1 = JOptionPane.showInputDialog("INGRESE FECHA INICIAL (AAAA-MM-DD)");
String f2 = JOptionPane.showInputDialog("INGRESE FECHA FINAL (AAAA-MM-DD)");
if (f1 == null || f2 == null) return; 

fecha  = java.sql.Date.valueOf(f1);   
fecha2 = java.sql.Date.valueOf(f2);
 try {
            conectarBD();
            Map parametro = new HashMap();
            parametro.put("Fechai", fecha);
            parametro.put("Fechaf", fecha2);
            //RUTA DEL ARCHIVO
            URL urlMaestro=getClass().getResource("reportVentaporfecha.jasper");
            //LLAMADO DEL ARCHIVO
            JasperReport reporte =(JasperReport) JRLoader.loadObject(urlMaestro);
            //LLENAMOS EL REPORTE
            JasperPrint jprint=JasperFillManager.fillReport(reporte, parametro,con);
            //VISTA DEL REPORTE
            JasperViewer view= new JasperViewer(jprint,false);
            //TITULO OPCIONAL
            view.setTitle("JOYERIA AMBER");
            //CIERRE DEL REPORTE
            view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            view.setVisible(true);
            con.close();
        } catch (JRException ex) {
            System.out.print(ex.getMessage());
        } catch (SQLException ex) {
           System.out.print(ex.getMessage());
        }
     }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        botsalir = new javax.swing.JButton();
        botrproveedor = new javax.swing.JButton();
        rpornombre = new javax.swing.JButton();
        botrgraficas = new javax.swing.JButton();
        botrproducto = new javax.swing.JButton();
        botrfecha = new javax.swing.JButton();
        botrgraficas1 = new javax.swing.JButton();
        botrgraficas2 = new javax.swing.JButton();
        botrgraficas3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/titulo.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 240, 90));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/marco_renew.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -50, 390, 600));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/loginImage.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 138, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 300, 430));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Rockwell Condensed", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("REPORTES");
        jLabel5.setOpaque(true);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 200, -1));

        botsalir.setBackground(new java.awt.Color(204, 0, 0));
        botsalir.setFont(new java.awt.Font("Rockwell Condensed", 1, 20)); // NOI18N
        botsalir.setText("SALIR");
        botsalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botsalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botsalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botsalirMouseExited(evt);
            }
        });
        botsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botsalirActionPerformed(evt);
            }
        });
        jPanel1.add(botsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, 290, 30));

        botrproveedor.setBackground(new java.awt.Color(204, 0, 0));
        botrproveedor.setFont(new java.awt.Font("Rockwell Condensed", 1, 20)); // NOI18N
        botrproveedor.setText("REPORTE DE PROVEEDORES");
        botrproveedor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botrproveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botrproveedorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botrproveedorMouseExited(evt);
            }
        });
        botrproveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botrproveedorActionPerformed(evt);
            }
        });
        jPanel1.add(botrproveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 290, 30));

        rpornombre.setBackground(new java.awt.Color(204, 0, 0));
        rpornombre.setFont(new java.awt.Font("Rockwell Condensed", 1, 20)); // NOI18N
        rpornombre.setText("REPORTE EXISTENCIA INVENT");
        rpornombre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        rpornombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rpornombreMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rpornombreMouseExited(evt);
            }
        });
        rpornombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rpornombreActionPerformed(evt);
            }
        });
        jPanel1.add(rpornombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 290, 30));

        botrgraficas.setBackground(new java.awt.Color(204, 0, 0));
        botrgraficas.setFont(new java.awt.Font("Rockwell Condensed", 1, 20)); // NOI18N
        botrgraficas.setText("REPORTE VENTA X DIA");
        botrgraficas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botrgraficas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botrgraficasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botrgraficasMouseExited(evt);
            }
        });
        botrgraficas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botrgraficasActionPerformed(evt);
            }
        });
        jPanel1.add(botrgraficas, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 290, 30));

        botrproducto.setBackground(new java.awt.Color(204, 0, 0));
        botrproducto.setFont(new java.awt.Font("Rockwell Condensed", 1, 20)); // NOI18N
        botrproducto.setText("REPORTE DE PRODUCTOS");
        botrproducto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botrproducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botrproductoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botrproductoMouseExited(evt);
            }
        });
        botrproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botrproductoActionPerformed(evt);
            }
        });
        jPanel1.add(botrproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 290, 30));

        botrfecha.setBackground(new java.awt.Color(204, 0, 0));
        botrfecha.setFont(new java.awt.Font("Rockwell Condensed", 1, 20)); // NOI18N
        botrfecha.setText("REPORTE VENTA X FECHA");
        botrfecha.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botrfecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botrfechaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botrfechaMouseExited(evt);
            }
        });
        botrfecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botrfechaActionPerformed(evt);
            }
        });
        jPanel1.add(botrfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 290, 30));

        botrgraficas1.setBackground(new java.awt.Color(204, 0, 0));
        botrgraficas1.setFont(new java.awt.Font("Rockwell Condensed", 1, 20)); // NOI18N
        botrgraficas1.setText("REPORTE VENTA PELICULA");
        botrgraficas1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botrgraficas1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botrgraficas1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botrgraficas1MouseExited(evt);
            }
        });
        botrgraficas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botrgraficas1ActionPerformed(evt);
            }
        });
        jPanel1.add(botrgraficas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, 290, 30));

        botrgraficas2.setBackground(new java.awt.Color(204, 0, 0));
        botrgraficas2.setFont(new java.awt.Font("Rockwell Condensed", 1, 20)); // NOI18N
        botrgraficas2.setText("REPOR VENTA BOLETO CONFITERIA");
        botrgraficas2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botrgraficas2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botrgraficas2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botrgraficas2MouseExited(evt);
            }
        });
        botrgraficas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botrgraficas2ActionPerformed(evt);
            }
        });
        jPanel1.add(botrgraficas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 290, 30));

        botrgraficas3.setBackground(new java.awt.Color(204, 0, 0));
        botrgraficas3.setFont(new java.awt.Font("Rockwell Condensed", 1, 20)); // NOI18N
        botrgraficas3.setText("REPORTE VENTAS");
        botrgraficas3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botrgraficas3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botrgraficas3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botrgraficas3MouseExited(evt);
            }
        });
        botrgraficas3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botrgraficas3ActionPerformed(evt);
            }
        });
        jPanel1.add(botrgraficas3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, 290, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botsalirActionPerformed
         dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_botsalirActionPerformed

    private void botsalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botsalirMouseEntered
            botsalir.setBackground(Color.BLACK);
            botsalir.setForeground(Color.WHITE);   // TODO add your handling code here:
    }//GEN-LAST:event_botsalirMouseEntered

    private void botsalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botsalirMouseExited
       botsalir.setBackground(new Color(204, 0, 0));
      botsalir.setForeground(new Color(0, 0, 0)); // TODO add your handling code here:
    }//GEN-LAST:event_botsalirMouseExited

    private void botrproveedorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botrproveedorMouseEntered
            botrproveedor.setBackground(Color.BLACK);
            botrproveedor.setForeground(Color.WHITE);
// TODO add your handling code here:
    }//GEN-LAST:event_botrproveedorMouseEntered

    private void botrproveedorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botrproveedorMouseExited
      botrproveedor.setBackground(new Color(204, 0, 0));
      botrproveedor.setForeground(new Color(0, 0, 0));
      
        // TODO add your handling code here:
    }//GEN-LAST:event_botrproveedorMouseExited

    private void botrproveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botrproveedorActionPerformed
     llamarReportes("reportProveedores.jasper");        // TODO add your handling code here:
    }//GEN-LAST:event_botrproveedorActionPerformed

    private void rpornombreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rpornombreMouseEntered
           rpornombre.setBackground(Color.BLACK);
            rpornombre.setForeground(Color.WHITE); // TODO add your handling code here:
    }//GEN-LAST:event_rpornombreMouseEntered

    private void rpornombreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rpornombreMouseExited
        rpornombre.setBackground(new Color(204, 0, 0));
      rpornombre.setForeground(new Color(0, 0, 0));// TODO add your handling code here:
    }//GEN-LAST:event_rpornombreMouseExited

    private void rpornombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rpornombreActionPerformed
      llamarReportes("reportInventarioaviso.jasper");        // TODO add your handling code here:
    }//GEN-LAST:event_rpornombreActionPerformed

    private void botrgraficasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botrgraficasMouseEntered
          botrgraficas.setBackground(Color.BLACK);
           botrgraficas.setForeground(Color.WHITE);  // TODO add your handling code here:
    }//GEN-LAST:event_botrgraficasMouseEntered

    private void botrgraficasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botrgraficasMouseExited
        botrgraficas.setBackground(new Color(204, 0, 0));
      botrgraficas.setForeground(new Color(0, 0, 0));// TODO add your handling code here:
    }//GEN-LAST:event_botrgraficasMouseExited

    private void botrgraficasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botrgraficasActionPerformed
      llamarReportes("reportVentapordia.jasper");        // TODO add your handling code here:
    }//GEN-LAST:event_botrgraficasActionPerformed

    private void botrproductoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botrproductoMouseEntered
           botrproducto.setBackground(Color.BLACK);
            botrproducto.setForeground(Color.WHITE); // TODO add your handling code here:
    }//GEN-LAST:event_botrproductoMouseEntered

    private void botrproductoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botrproductoMouseExited
    botrproducto.setBackground(new Color(204, 0, 0));
     botrproducto.setForeground(new Color(0, 0, 0));  // TODO add your handling code here:
    }//GEN-LAST:event_botrproductoMouseExited

    private void botrproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botrproductoActionPerformed
    llamarReportes("reportegrafico.jasper");     // TODO add your handling code here:
    }//GEN-LAST:event_botrproductoActionPerformed

    private void botrfechaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botrfechaMouseEntered
         botrfecha.setBackground(Color.BLACK);
           botrfecha.setForeground(Color.WHITE);   // TODO add your handling code here:
    }//GEN-LAST:event_botrfechaMouseEntered

    private void botrfechaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botrfechaMouseExited
     botrfecha.setBackground(new Color(204, 0, 0));
     botrfecha.setForeground(new Color(0, 0, 0));  // TODO add your handling code here:
    }//GEN-LAST:event_botrfechaMouseExited

    private void botrfechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botrfechaActionPerformed
     llamarReportePorfecha();        // TODO add your handling code here:
    }//GEN-LAST:event_botrfechaActionPerformed

    private void botrgraficas1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botrgraficas1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_botrgraficas1MouseEntered

    private void botrgraficas1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botrgraficas1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_botrgraficas1MouseExited

    private void botrgraficas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botrgraficas1ActionPerformed
     llamarReportes("reportedesempeñoPelicula.jasper");        // TODO add your handling code here:
    }//GEN-LAST:event_botrgraficas1ActionPerformed

    private void botrgraficas2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botrgraficas2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_botrgraficas2MouseEntered

    private void botrgraficas2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botrgraficas2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_botrgraficas2MouseExited

    private void botrgraficas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botrgraficas2ActionPerformed
     llamarReportes("reporteBoletoConfiteria.jasper");              // TODO add your handling code here:
    }//GEN-LAST:event_botrgraficas2ActionPerformed

    private void botrgraficas3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botrgraficas3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_botrgraficas3MouseEntered

    private void botrgraficas3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botrgraficas3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_botrgraficas3MouseExited

    private void botrgraficas3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botrgraficas3ActionPerformed
    llamarReportes("reporteVentas.jasper");        // TODO add your handling code here:
    }//GEN-LAST:event_botrgraficas3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Reporte dialog = new Reporte(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botrfecha;
    public javax.swing.JButton botrgraficas;
    public javax.swing.JButton botrgraficas1;
    public javax.swing.JButton botrgraficas2;
    public javax.swing.JButton botrgraficas3;
    public javax.swing.JButton botrproducto;
    public javax.swing.JButton botrproveedor;
    public javax.swing.JButton botsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JButton rpornombre;
    // End of variables declaration//GEN-END:variables
}
