/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

/**
 *
 * @author alexs
 */
public class Inventario_CRUD extends javax.swing.JDialog {

    String usuario;
    
    public Inventario_CRUD(java.awt.Frame parent, boolean modal, String user) {
        super(parent, modal);
        initComponents();
        this.usuario = user;
        jlbUsuarioProve.setText(usuario);
        jtfCodigo.setText("0");
        jtfMotivo.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlbUsuarioProve = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        botHome = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtfCodigo = new javax.swing.JTextField();
        jtfMotivo = new javax.swing.JTextField();
        jtfStockMax = new javax.swing.JTextField();
        botLimpiar = new javax.swing.JButton();
        botCrear = new javax.swing.JButton();
        botActualizar = new javax.swing.JButton();
        botLeer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInventario = new javax.swing.JTable();
        botBuscarINV = new javax.swing.JButton();
        botBuscarC = new javax.swing.JButton();
        botEliminar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jtfStockMin = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtfDescripcion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jdcFecha = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jtfCantidad1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cbxSI = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jdcVencimiento = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        cbxMove = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Rockwell Condensed", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("INVENTARIO");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 340, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoCinem.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 10, 380, 119));

        jlbUsuarioProve.setFont(new java.awt.Font("Rockwell Condensed", 1, 18)); // NOI18N
        jlbUsuarioProve.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jlbUsuarioProve, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 90, 100, 30));

        jLabel9.setFont(new java.awt.Font("Rockwell Condensed", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("USUARIO: ");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, 100, 30));

        botHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1.png"))); // NOI18N
        botHome.setBorderPainted(false);
        botHome.setContentAreaFilled(false);
        botHome.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/2.png"))); // NOI18N
        botHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botHomeActionPerformed(evt);
            }
        });
        jPanel2.add(botHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 10, 90, 70));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 950, 130));

        jPanel3.setBackground(new java.awt.Color(204, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CODIGO:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 72, 30));

        jLabel6.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("STOCK MAX:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 80, 30));

        jtfCodigo.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        jtfCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCodigoActionPerformed(evt);
            }
        });
        jPanel3.add(jtfCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 90, 40));

        jtfMotivo.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        jPanel3.add(jtfMotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 260, 40));

        jtfStockMax.setEditable(false);
        jtfStockMax.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        jPanel3.add(jtfStockMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 80, 40));

        botLimpiar.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        botLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-borrar-24.png"))); // NOI18N
        botLimpiar.setBorderPainted(false);
        botLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botLimpiarActionPerformed(evt);
            }
        });
        jPanel3.add(botLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 50, 50));

        botCrear.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        botCrear.setText("CREAR");
        botCrear.setBorderPainted(false);
        jPanel3.add(botCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 80, 40));

        botActualizar.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        botActualizar.setText("ACTUALIZAR");
        botActualizar.setBorderPainted(false);
        jPanel3.add(botActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, 110, 40));

        botLeer.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        botLeer.setText("LEER");
        botLeer.setBorderPainted(false);
        botLeer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botLeerActionPerformed(evt);
            }
        });
        jPanel3.add(botLeer, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, 90, 40));

        tblInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "PRODUCTO", "TIPO", "CANTIDAD", "FECHA", "MOTIVO", "VENCIMIENTO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblInventario);
        if (tblInventario.getColumnModel().getColumnCount() > 0) {
            tblInventario.getColumnModel().getColumn(0).setResizable(false);
            tblInventario.getColumnModel().getColumn(1).setResizable(false);
            tblInventario.getColumnModel().getColumn(2).setResizable(false);
            tblInventario.getColumnModel().getColumn(3).setResizable(false);
            tblInventario.getColumnModel().getColumn(4).setResizable(false);
            tblInventario.getColumnModel().getColumn(5).setResizable(false);
            tblInventario.getColumnModel().getColumn(6).setResizable(false);
        }

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 450, 240));

        botBuscarINV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        botBuscarINV.setToolTipText("BUSCAR INVENTARIO");
        botBuscarINV.setBorderPainted(false);
        jPanel3.add(botBuscarINV, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 50, 50));

        botBuscarC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        botBuscarC.setToolTipText("BUSCAR PRODUCTO");
        botBuscarC.setBorderPainted(false);
        jPanel3.add(botBuscarC, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 50, 50));

        botEliminar.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        botEliminar.setText("ELIMINAR");
        botEliminar.setBorderPainted(false);
        jPanel3.add(botEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 460, 100, 40));

        jLabel7.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("STOCK MIN:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 80, 30));

        jtfStockMin.setEditable(false);
        jtfStockMin.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        jPanel3.add(jtfStockMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 90, 40));

        jLabel5.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PRODUCTO:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 72, 30));

        jtfDescripcion.setEditable(false);
        jtfDescripcion.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        jPanel3.add(jtfDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 260, 40));

        jLabel10.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("CANTIDAD:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 72, 30));
        jPanel3.add(jdcFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 180, 30));

        jLabel8.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("FECHA DEL MOVIMIENTO:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 230, 30));

        jLabel11.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("MOVIMIENTO");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 90, 30));

        jtfCantidad1.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        jPanel3.add(jtfCantidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 260, 40));

        jLabel12.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("FECHA:");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 72, 30));

        cbxSI.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        cbxSI.setForeground(new java.awt.Color(255, 255, 255));
        cbxSI.setText("SI");
        cbxSI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSIActionPerformed(evt);
            }
        });
        jPanel3.add(cbxSI, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 40, 30));

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "NOMBRE", "PROVEEDOR", "STOCK MIN", "STOCK MAX"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblProductos);
        if (tblProductos.getColumnModel().getColumnCount() > 0) {
            tblProductos.getColumnModel().getColumn(0).setResizable(false);
            tblProductos.getColumnModel().getColumn(1).setResizable(false);
            tblProductos.getColumnModel().getColumn(2).setResizable(false);
            tblProductos.getColumnModel().getColumn(3).setResizable(false);
            tblProductos.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 450, 190));

        jLabel13.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("REQUIERE FECHA DE VENCIMIENTO?");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 230, 30));
        jPanel3.add(jdcVencimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 260, 30));

        jLabel14.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("MOTIVO:");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 72, 30));

        cbxMove.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        cbxMove.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE EL MOVE", "ENTRADA", "SALIDA" }));
        jPanel3.add(cbxMove, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 260, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 950, 520));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botHomeActionPerformed

    private void jtfCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCodigoActionPerformed

    private void botLeerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botLeerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botLeerActionPerformed

    private void cbxSIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxSIActionPerformed

    private void botLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botLimpiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventario_CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventario_CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventario_CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventario_CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Inventario_CRUD dialog = new Inventario_CRUD(new javax.swing.JFrame(), true, "ALX");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botActualizar;
    public javax.swing.JButton botBuscarC;
    public javax.swing.JButton botBuscarINV;
    public javax.swing.JButton botCrear;
    public javax.swing.JButton botEliminar;
    public javax.swing.JButton botHome;
    public javax.swing.JButton botLeer;
    public javax.swing.JButton botLimpiar;
    public javax.swing.JComboBox<String> cbxMove;
    public javax.swing.JCheckBox cbxSI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public com.toedter.calendar.JDateChooser jdcFecha;
    public com.toedter.calendar.JDateChooser jdcVencimiento;
    public javax.swing.JLabel jlbUsuarioProve;
    public javax.swing.JTextField jtfCantidad1;
    public javax.swing.JTextField jtfCodigo;
    public javax.swing.JTextField jtfDescripcion;
    public javax.swing.JTextField jtfMotivo;
    public javax.swing.JTextField jtfStockMax;
    public javax.swing.JTextField jtfStockMin;
    public javax.swing.JTable tblInventario;
    public javax.swing.JTable tblProductos;
    // End of variables declaration//GEN-END:variables
}
