/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.LoginControlador;
import java.awt.Color;
import modelo.ConsultaLogin;
import modelo.LoginPOO;

/**
 *
 * @author alexs
 */
public class Login extends javax.swing.JFrame {

    String usuario, contrasena;

    public Login(String usuario, String contrasena) {
        initComponents();
        this.setLocationRelativeTo(null);
      
        this.usuario = usuario;
        this.contrasena = contrasena;
        jtfUsuarioLog.setText(usuario);
        jtfContrasenaLog.setText(contrasena);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jtfUsuarioLog = new javax.swing.JTextField();
        jtfContrasenaLog = new javax.swing.JPasswordField();
        botSalir = new javax.swing.JButton();
        botIniciar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/loginImage.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 170, 370, 300));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/titulo.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 240, 90));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/marco_renew.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -50, 380, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, -1, 480));

        jPanel3.setBackground(new java.awt.Color(204, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/login.png"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 160, 80));

        jLabel4.setFont(new java.awt.Font("Rockwell Condensed", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ingresar");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 110, -1));

        jLabel5.setFont(new java.awt.Font("Rockwell Condensed", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("INICIAR SESION");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 200, -1));

        jLabel6.setFont(new java.awt.Font("Rockwell Condensed", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("usuario");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 200, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 300, 20));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 300, 20));

        jtfUsuarioLog.setBackground(new java.awt.Color(204, 0, 0));
        jtfUsuarioLog.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        jtfUsuarioLog.setForeground(new java.awt.Color(255, 255, 255));
        jtfUsuarioLog.setBorder(null);
        jPanel3.add(jtfUsuarioLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 300, 40));

        jtfContrasenaLog.setBackground(new java.awt.Color(204, 0, 0));
        jtfContrasenaLog.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        jtfContrasenaLog.setForeground(new java.awt.Color(255, 255, 255));
        jtfContrasenaLog.setBorder(null);
        jPanel3.add(jtfContrasenaLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 300, 40));

        botSalir.setFont(new java.awt.Font("Rockwell Condensed", 1, 36)); // NOI18N
        botSalir.setForeground(new java.awt.Color(255, 255, 255));
        botSalir.setText("X");
        botSalir.setBorder(null);
        botSalir.setBorderPainted(false);
        botSalir.setContentAreaFilled(false);
        botSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botSalirMouseExited(evt);
            }
        });
        botSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botSalirActionPerformed(evt);
            }
        });
        jPanel3.add(botSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 60));

        botIniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotIniciar3.png"))); // NOI18N
        botIniciar.setToolTipText("ACCION");
        botIniciar.setBorderPainted(false);
        botIniciar.setContentAreaFilled(false);
        botIniciar.setFocusPainted(false);
        botIniciar.setFocusable(false);
        botIniciar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botiniciar.png"))); // NOI18N
        botIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botIniciarActionPerformed(evt);
            }
        });
        jPanel3.add(botIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 100, 100));

        jLabel8.setFont(new java.awt.Font("Rockwell Condensed", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("contraseña");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 200, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 390, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botSalirActionPerformed

    private void botSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botSalirMouseEntered

        botSalir.setForeground(Color.BLACK);
    }//GEN-LAST:event_botSalirMouseEntered

    private void botSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botSalirMouseExited
      
        botSalir.setForeground(Color.WHITE);
    }//GEN-LAST:event_botSalirMouseExited

    private void botIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botIniciarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botIniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ConsultaLogin conexion = new ConsultaLogin();
                Login form = new Login("", "");
                LoginPOO user = new LoginPOO();
                Registro formR = null;
                Principal formprin = null;
                new LoginControlador(form, user, conexion,formR, formprin);
                form.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botIniciar;
    public javax.swing.JButton botSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JPasswordField jtfContrasenaLog;
    public javax.swing.JTextField jtfUsuarioLog;
    // End of variables declaration//GEN-END:variables
}
