/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Reportes.Reporte;
import java.awt.Color;

/**
 *
 * @author alexs
 */
public class Principal extends javax.swing.JFrame {

    String usuario;

    public Principal(String user) {
        initComponents();
        this.usuario = user;
        jlbUsuarioMain.setText(usuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        botResgistrar = new javax.swing.JButton();
        botsalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlbUsuarioMain = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botSalas = new javax.swing.JButton();
        botInformacion = new javax.swing.JButton();
        botPeliculas = new javax.swing.JButton();
        botProveedores = new javax.swing.JButton();
        botProductos = new javax.swing.JButton();
        botVentas = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        botReportes = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        botHorarios = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));
        jPanel1.setForeground(new java.awt.Color(153, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botResgistrar.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        botResgistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/registro1.png"))); // NOI18N
        botResgistrar.setBorderPainted(false);
        botResgistrar.setContentAreaFilled(false);
        botResgistrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/registro2.png"))); // NOI18N
        botResgistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botResgistrarActionPerformed(evt);
            }
        });
        jPanel1.add(botResgistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 80, 70));

        botsalir.setFont(new java.awt.Font("Rockwell Condensed", 1, 48)); // NOI18N
        botsalir.setText("X");
        botsalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botsalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botsalirMouseExited(evt);
            }
        });
        botsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botsalirActionPerformed(evt);
            }
        });
        jPanel1.add(botsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, 70, 70));

        jLabel1.setFont(new java.awt.Font("Rockwell Condensed", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("WELCOME TO CINEMANIA ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 270, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bottomLine.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -330, 960, 410));

        jlbUsuarioMain.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        jlbUsuarioMain.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jlbUsuarioMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 110, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/popcorn.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 530, 530));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/UpperLine.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 520, 890, 510));

        botSalas.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        botSalas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salas1.png"))); // NOI18N
        botSalas.setText("SALAS");
        botSalas.setToolTipText("SALAS");
        botSalas.setBorderPainted(false);
        botSalas.setContentAreaFilled(false);
        botSalas.setFocusPainted(false);
        botSalas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salas2.png"))); // NOI18N
        jPanel1.add(botSalas, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 100, 100));

        botInformacion.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        botInformacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/info1.png"))); // NOI18N
        botInformacion.setText("INFORMACION");
        botInformacion.setToolTipText("INFORMACION");
        botInformacion.setBorderPainted(false);
        botInformacion.setContentAreaFilled(false);
        botInformacion.setFocusPainted(false);
        botInformacion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/info2.png"))); // NOI18N
        botInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botInformacionActionPerformed(evt);
            }
        });
        jPanel1.add(botInformacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 110, 60));

        botPeliculas.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        botPeliculas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/peli1.png"))); // NOI18N
        botPeliculas.setText("PELICULAS");
        botPeliculas.setToolTipText("PELICULAS");
        botPeliculas.setBorderPainted(false);
        botPeliculas.setContentAreaFilled(false);
        botPeliculas.setFocusPainted(false);
        botPeliculas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/peli2.png"))); // NOI18N
        botPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botPeliculasActionPerformed(evt);
            }
        });
        jPanel1.add(botPeliculas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 130, 90));

        botProveedores.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        botProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/proveedores.png"))); // NOI18N
        botProveedores.setText("HORARIOS");
        botProveedores.setToolTipText("HORARIOS");
        botProveedores.setBorderPainted(false);
        botProveedores.setContentAreaFilled(false);
        botProveedores.setFocusPainted(false);
        botProveedores.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pro2.png"))); // NOI18N
        botProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botProveedoresActionPerformed(evt);
            }
        });
        jPanel1.add(botProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 80, 90));

        botProductos.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        botProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/produ1.png"))); // NOI18N
        botProductos.setText("PRODUCTOS");
        botProductos.setToolTipText("PRODUCTOS");
        botProductos.setBorderPainted(false);
        botProductos.setContentAreaFilled(false);
        botProductos.setFocusPainted(false);
        botProductos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/produ2.png"))); // NOI18N
        jPanel1.add(botProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 120, 100));

        botVentas.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        botVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boleto1.png"))); // NOI18N
        botVentas.setText("BOLETOS");
        botVentas.setToolTipText("BOLETOS");
        botVentas.setBorderPainted(false);
        botVentas.setContentAreaFilled(false);
        botVentas.setFocusPainted(false);
        botVentas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boleto2.png"))); // NOI18N
        jPanel1.add(botVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 150, 70));

        jLabel7.setFont(new java.awt.Font("Rockwell Condensed", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PELICULAS");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 100, 30));

        jLabel8.setFont(new java.awt.Font("Rockwell Condensed", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("SALAS");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 70, 30));

        jLabel9.setFont(new java.awt.Font("Rockwell Condensed", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("CARTELERA");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 90, 30));

        jLabel10.setFont(new java.awt.Font("Rockwell Condensed", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("REPORTES");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, 100, 30));

        jLabel11.setFont(new java.awt.Font("Rockwell Condensed", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("REGISTRAR");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 480, 100, 30));

        jLabel13.setFont(new java.awt.Font("Rockwell Condensed", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("VENTAS");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, 100, 30));

        jLabel12.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("USUARIO");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 70, 30));

        botReportes.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        botReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reporyes.png"))); // NOI18N
        botReportes.setText("HORARIOS");
        botReportes.setToolTipText("HORARIOS");
        botReportes.setBorderPainted(false);
        botReportes.setContentAreaFilled(false);
        botReportes.setFocusPainted(false);
        botReportes.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rep2.png"))); // NOI18N
        botReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botReportesActionPerformed(evt);
            }
        });
        jPanel1.add(botReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 90, 90));

        jLabel14.setFont(new java.awt.Font("Rockwell Condensed", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("PROVEEDORES");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 120, 30));

        botHorarios.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        botHorarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/horario.png"))); // NOI18N
        botHorarios.setText("HORARIOS");
        botHorarios.setToolTipText("HORARIOS");
        botHorarios.setBorderPainted(false);
        botHorarios.setContentAreaFilled(false);
        botHorarios.setFocusPainted(false);
        botHorarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botHorariosActionPerformed(evt);
            }
        });
        jPanel1.add(botHorarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 90, 80));

        jLabel15.setFont(new java.awt.Font("Rockwell Condensed", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("PRODUCTOS");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 100, 30));

        jLabel16.setFont(new java.awt.Font("Rockwell Condensed", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("INFORMACION");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, 130, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 850, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botPeliculasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botPeliculasActionPerformed

    private void botInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botInformacionActionPerformed
        //new Informacion().setVisible(true);
    }//GEN-LAST:event_botInformacionActionPerformed

    private void botsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botsalirActionPerformed

    }//GEN-LAST:event_botsalirActionPerformed

    private void botsalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botsalirMouseEntered
        botsalir.setBackground(Color.red);
        botsalir.setForeground(Color.WHITE);
    }//GEN-LAST:event_botsalirMouseEntered

    private void botsalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botsalirMouseExited
        botsalir.setBackground(Color.WHITE);
        botsalir.setForeground(Color.black);
    }//GEN-LAST:event_botsalirMouseExited

    private void botProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botProveedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botProveedoresActionPerformed

    private void botHorariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botHorariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botHorariosActionPerformed

    private void botReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botReportesActionPerformed
    Reporte dlg = new Reporte(this, true); 
    dlg.setLocationRelativeTo(this);    
    dlg.setVisible(true);         
    }//GEN-LAST:event_botReportesActionPerformed

    private void botResgistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botResgistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botResgistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal("alx").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botHorarios;
    public javax.swing.JButton botInformacion;
    public javax.swing.JButton botPeliculas;
    public javax.swing.JButton botProductos;
    public javax.swing.JButton botProveedores;
    public javax.swing.JButton botReportes;
    public javax.swing.JButton botResgistrar;
    public javax.swing.JButton botSalas;
    public javax.swing.JButton botVentas;
    public javax.swing.JButton botsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlbUsuarioMain;
    // End of variables declaration//GEN-END:variables
}
