/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

/**
 *
 * @author alexs
 */
public class Registro extends javax.swing.JDialog {

    /**
     * Creates new form Registro
     */
    public Registro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        jtfCodigo.setText("0");
        jtfNombreLog2.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfApellidoLog = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbxRoles = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtfCodigo = new javax.swing.JTextField();
        jtfUsuarioLog = new javax.swing.JTextField();
        botEliminar = new javax.swing.JButton();
        botCrear = new javax.swing.JButton();
        botActualizar = new javax.swing.JButton();
        botLeer = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jtfNombreLog2 = new javax.swing.JTextField();
        jtfContrasena = new javax.swing.JPasswordField();
        botBuscarC = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblRegistro = new javax.swing.JTable();
        botLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Rockwell Condensed", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Roles:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 100, 60));
        jPanel1.add(jtfApellidoLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 180, 30));

        jLabel2.setFont(new java.awt.Font("Rockwell Condensed", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("REGISTRO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 170, 40));

        jLabel3.setFont(new java.awt.Font("Rockwell Condensed", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Contraseña:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 120, 60));

        jLabel4.setFont(new java.awt.Font("Rockwell Condensed", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Apellido:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 100, 60));

        cbxRoles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE EL ROL ", "Administrador ", "Cajero" }));
        jPanel1.add(cbxRoles, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 210, 30));

        jLabel5.setFont(new java.awt.Font("Rockwell Condensed", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("codigo:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 90, 40));

        jLabel6.setFont(new java.awt.Font("Rockwell Condensed", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Usuario:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 90, 60));
        jPanel1.add(jtfCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 100, 30));
        jPanel1.add(jtfUsuarioLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 190, 30));

        botEliminar.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        botEliminar.setText("ELIMINAR");
        botEliminar.setBorderPainted(false);
        jPanel1.add(botEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, 110, 60));

        botCrear.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        botCrear.setText("CREAR");
        botCrear.setBorderPainted(false);
        botCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botCrearActionPerformed(evt);
            }
        });
        jPanel1.add(botCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 110, 60));

        botActualizar.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        botActualizar.setText("ACTUALIZAR");
        botActualizar.setBorderPainted(false);
        jPanel1.add(botActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 110, 60));

        botLeer.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        botLeer.setText("LEER");
        botLeer.setBorderPainted(false);
        jPanel1.add(botLeer, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 110, 60));

        jLabel7.setFont(new java.awt.Font("Rockwell Condensed", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nombre:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 90, 40));
        jPanel1.add(jtfNombreLog2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 180, 30));
        jPanel1.add(jtfContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 210, 30));

        botBuscarC.setText("buscar");
        jPanel1.add(botBuscarC, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 70, 50));

        jtblRegistro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "NOMBRE", "APELLIDO", "USUARIO", "ROL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtblRegistro);
        if (jtblRegistro.getColumnModel().getColumnCount() > 0) {
            jtblRegistro.getColumnModel().getColumn(0).setResizable(false);
            jtblRegistro.getColumnModel().getColumn(1).setResizable(false);
            jtblRegistro.getColumnModel().getColumn(2).setResizable(false);
            jtblRegistro.getColumnModel().getColumn(3).setResizable(false);
            jtblRegistro.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, 320, 310));

        botLimpiar.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        botLimpiar.setText("LIMPIAR");
        botLimpiar.setBorderPainted(false);
        botLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(botLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 90, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botCrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botCrearActionPerformed

    private void botLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botLimpiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Registro dialog = new Registro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botActualizar;
    public javax.swing.JButton botBuscarC;
    public javax.swing.JButton botCrear;
    public javax.swing.JButton botEliminar;
    public javax.swing.JButton botLeer;
    public javax.swing.JButton botLimpiar;
    public javax.swing.JComboBox<String> cbxRoles;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    public javax.swing.JTable jtblRegistro;
    public javax.swing.JTextField jtfApellidoLog;
    public javax.swing.JTextField jtfCodigo;
    public javax.swing.JPasswordField jtfContrasena;
    public javax.swing.JTextField jtfNombreLog2;
    public javax.swing.JTextField jtfUsuarioLog;
    // End of variables declaration//GEN-END:variables
}
