/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

/**
 *
 * @author alexs
 */
public class Salas_CRUD extends javax.swing.JDialog {

    String usuario;

    public Salas_CRUD(java.awt.Frame parent, boolean modal, String user) {
        super(parent, modal);
        initComponents();
        this.usuario=user;
        jlbUsuarioSala.setText(usuario);
        jtfCodigoSala.setText("0");
        jtfNombreSala.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlbUsuarioSala = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        botHome = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtfTipo = new javax.swing.JTextField();
        jtfCodigoSala = new javax.swing.JTextField();
        jtfNombreSala = new javax.swing.JTextField();
        jtfCapacidadSal = new javax.swing.JTextField();
        botBuscarT = new javax.swing.JButton();
        botLimpiarSala = new javax.swing.JButton();
        botCrearSala = new javax.swing.JButton();
        botActualizarSala = new javax.swing.JButton();
        botLeerSala = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSala = new javax.swing.JTable();
        botBuscarC = new javax.swing.JButton();
        botEliminarSala = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Rockwell Condensed", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SALAS");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 160, 34));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoCinem.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 10, 380, 119));

        jlbUsuarioSala.setFont(new java.awt.Font("Rockwell Condensed", 1, 18)); // NOI18N
        jlbUsuarioSala.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jlbUsuarioSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 90, 100, 30));

        jLabel9.setFont(new java.awt.Font("Rockwell Condensed", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("USUARIO: ");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, 100, 30));

        botHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1.png"))); // NOI18N
        botHome.setBorderPainted(false);
        botHome.setContentAreaFilled(false);
        botHome.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/2.png"))); // NOI18N
        botHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botHomeActionPerformed(evt);
            }
        });
        jPanel2.add(botHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 10, 90, 70));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 940, 130));

        jPanel3.setBackground(new java.awt.Color(204, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SALA ");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 72, 30));

        jLabel4.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CODIGO");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 72, 30));

        jLabel5.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("TIPO DE SALA");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 102, 30));

        jLabel6.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("CAPACIDAD");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 89, 30));

        jtfTipo.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        jPanel3.add(jtfTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 220, 50));

        jtfCodigoSala.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        jPanel3.add(jtfCodigoSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 220, 50));

        jtfNombreSala.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        jPanel3.add(jtfNombreSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 220, 50));

        jtfCapacidadSal.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        jPanel3.add(jtfCapacidadSal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 220, 50));

        botBuscarT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Lupa2.png"))); // NOI18N
        botBuscarT.setBorderPainted(false);
        jPanel3.add(botBuscarT, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 80, 60));

        botLimpiarSala.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        botLimpiarSala.setText("LIMPIAR");
        botLimpiarSala.setBorderPainted(false);
        botLimpiarSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botLimpiarSalaActionPerformed(evt);
            }
        });
        jPanel3.add(botLimpiarSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 100, 160, 50));

        botCrearSala.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        botCrearSala.setText("CREAR");
        botCrearSala.setBorderPainted(false);
        jPanel3.add(botCrearSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 160, 50));

        botActualizarSala.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        botActualizarSala.setText("ACTUALIZAR");
        botActualizarSala.setBorderPainted(false);
        jPanel3.add(botActualizarSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 30, 160, 50));

        botLeerSala.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        botLeerSala.setText("LEER");
        botLeerSala.setBorderPainted(false);
        jPanel3.add(botLeerSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, 160, 50));

        tblSala.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "SALA", "CAPACIDAD", "TIPO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSala);
        if (tblSala.getColumnModel().getColumnCount() > 0) {
            tblSala.getColumnModel().getColumn(0).setResizable(false);
            tblSala.getColumnModel().getColumn(1).setResizable(false);
            tblSala.getColumnModel().getColumn(2).setResizable(false);
            tblSala.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 890, 160));

        botBuscarC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Lupa2.png"))); // NOI18N
        botBuscarC.setBorderPainted(false);
        jPanel3.add(botBuscarC, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 80, 60));

        botEliminarSala.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        botEliminarSala.setText("ELIMINAR");
        botEliminarSala.setBorderPainted(false);
        jPanel3.add(botEliminarSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 180, 160, 50));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 940, 470));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botHomeActionPerformed

    private void botLimpiarSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botLimpiarSalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botLimpiarSalaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Salas_CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Salas_CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Salas_CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Salas_CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Salas_CRUD dialog = new Salas_CRUD(new javax.swing.JFrame(), true, "ALX");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botActualizarSala;
    public javax.swing.JButton botBuscarC;
    public javax.swing.JButton botBuscarT;
    public javax.swing.JButton botCrearSala;
    public javax.swing.JButton botEliminarSala;
    public javax.swing.JButton botHome;
    public javax.swing.JButton botLeerSala;
    public javax.swing.JButton botLimpiarSala;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel jlbUsuarioSala;
    public javax.swing.JTextField jtfCapacidadSal;
    public javax.swing.JTextField jtfCodigoSala;
    public javax.swing.JTextField jtfNombreSala;
    public javax.swing.JTextField jtfTipo;
    public javax.swing.JTable tblSala;
    // End of variables declaration//GEN-END:variables
}
